### ISSUE TITLE
Resolving configuration 'api' directly is not allowed

### ISSUE THREAD

**Issue by justinpitts** [nebula-plugins/gradle-lint-plugin#161] opened 2018-03-12 04:52 UTC
https://github.com/nebula-plugins/gradle-lint-plugin/blob/b513e14f13a835999870cceffb6b0ec39027e92b/src/main/groovy/com/netflix/nebula/lint/rule/dependency/AbstractDuplicateDependencyClassRule.groovy#L20

I am trying to use lint with a project that has the java-library plugin, and I'm getting an IllegalStateException at line 20 when I attempt to `gradle lint`

I think the discussion at https://discuss.gradle.org/t/3-4-rc-1-3-3-resolving-configurations-may-be-disallowed-and-throw-illegalstateexception/21470 may be relevant here, and firstOrderModuleIds may need a check to ensure it isn't trying to resolve an unallowed configuration.

**Comment by DanielThomas** [comment] 2018-03-12 16:42
What version are lint are you using? We filter unresolvable configurations from consideration in the dependency rules.

**Comment by justinpitts** [comment] 2018-03-12 16:58
I've tried 8.3.2 and 8.3.1.

Where is that filter implemented?

**Comment by DanielThomas** [comment] 2018-03-12 21:02
Ah, looks like that rule doesn't have the condition. It should be using this:

https://github.com/nebula-plugins/gradle-lint-plugin/blob/b513e14f13a835999870cceffb6b0ec39027e92b/src/main/groovy/com/netflix/nebula/lint/rule/dependency/DependencyService.groovy#L369

**Comment by philippebn** [comment] 2018-03-23 14:33
Same here on a project
Caused by: java.lang.IllegalStateException: Resolving configuration 'api' directly is not allowed

**Comment by OdysseusLives** [comment] 2018-09-06 20:52
Resolved in v9.3.4

**Closed** 2018-09-06 20:53 UTC
Labels: bug
