### ISSUE TITLE
Gradle 6.0 warning

### ISSUE THREAD

**Issue by bric3** [nebula-plugins/gradle-lint-plugin#236] opened 2019-04-04 11:35 UTC
Just declaring the plugin raises these warnings with the `org.gradle.warning.mode` property set to all : 

```
The configuration :detachedConfiguration1139 was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project.  See https://docs.gradle.org/5.3.1/userguide/troubleshooting_dependency_resolution.html#sub:configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.
```

I don't know if this is gonna be a problem, but I'd rather report it now. These warnings do not appear if the warning mode is set to a _lower_ mode (`summary`, or `off` of course).

**Comment by xenomachina** [comment] 2019-05-20 21:09
We're getting a slightly different warning, but I suspect that the root cause is the same:

> $ ./gradlew --warning-mode all clean  
> The configuration :compile was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project.  See https://docs.gradle.org/5.4.1/userguide/troubleshooting_dependency_resolution.html#sub:configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.  
> The configuration :testCompile was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project.  See https://docs.gradle.org/5.4.1/userguide/troubleshooting_dependency_resolution.html#sub:configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.  
>  
> BUILD SUCCESSFUL in 1s  
> 1 actionable task: 1 executed

This is with Gradle 5.4.1,  nebula.lint 11.5.0.

**Comment by rpalcolea** [comment] 2019-09-17 19:55
Hi folks, I believe this should be fixed in newest versions of the plugin as we have worked on removing deprecation warnings and how we access the configurations from it.

Can you give it a shot and let us know?

**Comment by bric3** [comment] 2019-09-18 10:19
@rpalcolea No more warning for me using Gradle 5.5.1

**Comment by rpalcolea** [comment] 2019-09-18 20:27
👍 thanks for confirming, closing this now

**Closed by rpalcolea** 2019-09-18 20:27 UTC
